Select a.CID,
       to_char(a.START_TIME,'yyyy-MM-dd') as START_TIME,
       a.BUSINESS_NAME,
       a.SFZH,
       a.NEED_INVESTIGATION,
       a.STATUS,
       a.LOG_ID,
       b.CID,
       b.ORGANIZATION_CODE,
       b.SOCIAL_UNITY_CREDIT_CODE,
       b.COMPANY_NAME,
       b.COMPANY_ADDRESS,
       b.CONTACT_NUMBER,
       b.DWLB,
       b.SSQX,
       b.HYLB,
       b.REGISTER_ADDRESS,
       b.REGISTER_DATE,
       b.REGISTER_SSQX,
       b.VALID_PERIOD,
       b.DWLX,
       b.PERSON_IN_CHARGE,
       b.PERSON_IN_CHARGE_NUMBER,
       b.PERSON_IN_CHARGE_ADDRESS,
       b.REGISTER_MONEY,
       b.SOCIAL_INSURANCE_CODE,
       b.PAYMENT_STATUS,
       b.DATA_SOURCE,
       b.LOG_ID,
       b.SSJD,
       b.SSJW,
       trunc((to_char(sysdate, 'yyyyMMdd') - to_char(to_date(substr(a.sfzh, 7, 8), 'yyyyMMdd'),'yyyyMMdd')) / 10000) as age,
       mod((TO_NUMBER(substr(a.sfzh, 17, 1))),2) as sex
  from T_HELP_BUSINESS_INFO a, T_COMPANY_INFO b
 where a.cid = b.cid;
 
 select * from T_HELP_BUSINESS_INFO for update;
